server:
  shutdown: graceful
  port: ${SPRING_PORT}

user:
  base:
    image: ${BASE_IMG}

app:
  api:
    base: ${API_BASE}
    admin: ${API_ADMIN}
  auth:
    secret: ${AUTH_SECRET}
    accessExpired: ${AUTH_ACCESS_PERIOD}
    refreshExpired: ${AUTH_REFRESH_PERIOD}

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}

fcm:
  url: ${FCM_URL}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto: false
    region:
      static: ${S3_REGION}
    credentials:
      access_key: ${S3_ACCESS}
      secret_key: ${S3_SECRET}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: ${DB_DDL}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
